# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov_json_formatter` gem.
# Please instead update this file by running `bin/tapioca gem simplecov_json_formatter`.


# source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#7
module SimpleCov; end

# source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#8
module SimpleCov::Formatter; end

# source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#9
class SimpleCov::Formatter::JSONFormatter
  # source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#10
  def format(result); end

  private

  # source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#25
  def export_formatted_result(result_hash); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#20
  def format_result(result); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter.rb#30
  def output_message(result); end
end

# source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#3
module SimpleCovJSONFormatter; end

# source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#4
class SimpleCovJSONFormatter::ResultExporter
  # @return [ResultExporter] a new instance of ResultExporter
  #
  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#7
  def initialize(result_hash); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#11
  def export; end

  private

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#23
  def export_path; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#19
  def json_result; end
end

# source://simplecov_json_formatter//lib/simplecov_json_formatter/result_exporter.rb#5
SimpleCovJSONFormatter::ResultExporter::FILENAME = T.let(T.unsafe(nil), String)

# source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#6
class SimpleCovJSONFormatter::ResultHashFormatter
  # @return [ResultHashFormatter] a new instance of ResultHashFormatter
  #
  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#7
  def initialize(result); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#11
  def format; end

  private

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#20
  def format_files; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#27
  def format_groups; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#47
  def format_source_file(source_file); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/result_hash_formatter.rb#37
  def formatted_result; end
end

# source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#4
class SimpleCovJSONFormatter::SourceFileFormatter
  # @return [SourceFileFormatter] a new instance of SourceFileFormatter
  #
  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#5
  def initialize(source_file); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#10
  def format; end

  private

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#26
  def branch_coverage; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#41
  def branches; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#20
  def line_coverage; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#32
  def lines; end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#56
  def parse_branch(branch); end

  # source://simplecov_json_formatter//lib/simplecov_json_formatter/source_file_formatter.rb#50
  def parse_line(line); end
end
