inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - ".mdlrc"

Minitest:
  Enabled: true

Minitest/MultipleAssertions:
  Max: 6

Rails:
  Enabled: true

Rails/RefuteMethods:
  EnforcedStyle: refute
