# typed: strict
# # DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Plus instead update this file by running `bin/tapioca require`.
# frozen_string_literal: true

require "minitest/autorun"
require "sorbet-runtime"
require "active_support"
require "active_support/core_ext/numeric/time.rb"
require "mocha/minitest"
