name: Automerge Dependabot

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: |
          (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' ||
           steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major version updates
        if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Hi @${{ github.repository_owner }}! This PR is for a major version update and will not be auto-merged. Please review it manually."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
