name: Check Pipeline

on:
  push:
    branches-ignore:
        - main
    paths-ignore:
        - ".gitignore"
        - "README.md"
    tags-ignore:
        - v*

permissions:
  contents: write
  checks: write

jobs:
  update-rbis:
    name: Update RBI Files
    uses: ./.github/workflows/rbi-updater.yml
    secrets: inherit

  ci:
    needs: update-rbis
    if: always() && contains(needs.*.result, 'success')
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets: inherit
