name: Performance Monitor

on:
  workflow_run:
    workflows: ["CI", "Check Pipeline"]
    types: [completed]
  schedule:
    # Daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: read

jobs:
  monitor:
    name: Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Simple Workflow Monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Workflow Performance Report" > performance-report.md
          echo "Generated on: $(date)" >> performance-report.md
          echo "" >> performance-report.md

          # Get recent workflow runs (simple format)
          echo "## Recent Workflow Runs" >> performance-report.md
          gh run list --limit 10 >> performance-report.md
          echo "" >> performance-report.md

          # Check for currently running workflows
          echo "## Currently Running Workflows" >> performance-report.md
          RUNNING_COUNT=$(gh run list --status in_progress | wc -l)
          if [ "$RUNNING_COUNT" -gt 1 ]; then  # -gt 1 because header counts as 1
            echo "⚠️  Found $((RUNNING_COUNT - 1)) running workflows:" >> performance-report.md
            gh run list --status in_progress >> performance-report.md
          else
            echo "✅ No workflows currently running" >> performance-report.md
          fi
          echo "" >> performance-report.md

          # Simple health check
          echo "## Workflow Health Check" >> performance-report.md
          FAILED_COUNT=$(gh run list --limit 20 --status failure | wc -l)
          if [ "$FAILED_COUNT" -gt 1 ]; then  # -gt 1 because header counts as 1
            echo "⚠️  Found $((FAILED_COUNT - 1)) failed runs in last 20:" >> performance-report.md
          else
            echo "✅ No recent failures detected" >> performance-report.md
          fi

          # Display the report
          echo "Performance report generated:"
          cat performance-report.md

      - name: Upload Performance Report
        uses: actions/upload-artifact@v5
        with:
          name: performance-report-${{ github.run_number }}
          path: performance-report.md
          retention-days: 30
